// svelte/src/App.svelte
<script lang="ts">
  import "./app.css";
  import { v4 as uuid } from 'uuid';
  import {
    MaterialApp,
    AppBar,
    TextField,
    Card,
    CardText,
    CardTitle,
    Select,
    Button,
  } from "svelte-materialify";

  interface Note {
    id: string;
    title: string;
    text: string;
    color: string;
  }

  let currentNoteIndex = 0;
  let notes: Note[] = [];
  //color options
  const items = ["blue", "red", "black", "white", "green", "indigo", "purple"];
  $: noteTitle = "";
  $: noteText = "";
  $: noteColor = "";

  const clearNoteState = () => {
    noteTitle = "";
    noteText = "";
    currentNoteIndex++;
  };

  function addNote() {
    notes = [
      ...notes,
      {
        id: uuid(),
        title: noteTitle,
        text: noteText,
        color: noteColor,
      },
    ];
    clearNoteState();
  }

  function deleteNote(id: string) {
    notes = notes.filter((note) => id != note.id);
  }
</script>

<MaterialApp>
  <AppBar
    >Svelte Notes
    <TextField class="ma-4" bind:value={noteTitle}>Note name</TextField>
    <TextField class="ma-4" bind:value={noteText}>Text</TextField>
    <Select {items} class="ma-4" bind:value={noteColor} placeholder="Color" />
    <Button on:click={() => addNote()}>Add note</Button>
  </AppBar>

  <div class="note-container pa-4 d-flex flex-wrap justify-start">
    {#each notes as note}
      <Card
        class="note-card pa-4 ma-4 {note.color} {note.color === 'black' &&
          'theme--dark'}"
      >
        <Button on:click={() => deleteNote(note.id)}>Delete</Button>
        <CardTitle>{note.title}</CardTitle>
        <CardText>{note.text}</CardText>
      </Card>
    {/each}
  </div>
</MaterialApp>

// react/src/App.tsx
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from "./components/NavBar"
import NotesView from "./components/NotesView"
import { v4 as uuid } from 'uuid';
import { useState } from 'react';

export interface Note {
  id: string;
  title: string;
  text: string;
  color: string;
}

const App = () => {
  const [ notes, setNotes ] = useState<Note[]>([]);
  const [ noteCount, setNoteCount ] = useState([]);

  const possibleNoteColors = ["blue", "red", "black", "white", "green", "indigo", "purple"];

  const addNoteHandler = (_title: string, _text: string, _color: string) => {
    setNotes(notes => [...notes, {
      id: uuid(),
      title: _title,
      text: _text,
      color: _color
    }])
  }

  const deleteNoteHandler = (id: string) => {
    setNotes((prevNotes) => {
      return (prevNotes.filter((note) => {
        return id !== note.id
      }))
    })
  }

  return (
    <>
      <NavBar addNoteHandler={addNoteHandler} noteColors={possibleNoteColors} amountOfNotes={notes.length} />
      <NotesView notes={notes} deleteNote={deleteNoteHandler} />
    </>
  )
}

export default App
